#spring.jpa.open-in-view=true
#
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password= ${DATABASE_PASSWORD}

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true
#
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
#spring.security.user.name=admin
#spring.security.user.password=admin
#spring.security.user.roles=USER

#server.port=8080

#When spring.jpa.open-in-view is set
#to true (which is the default in Spring Boot),
#a filter or interceptor is registered that opens
#the persistence context at the beginning of a request and
#closes it at the end. This means that entities fetched
#within a transaction, even after the transaction has committed,
#can still be lazily loaded in the view layer without
#encountering LazyInitializationExceptions.